# 電力計測の関連定数
MEASURE_INTERVAL = 60
CHANNEL_CHANGE_INTERVAL = 10
CONVERSION_CONSTANT = 30 # 100 ohm
VOLTAGE = 100
TO_KILOWATT = 0.001

# ハートビート関連定数 ( slee-Pi 用)
FLIP_INTERVAL = 500
HEARTBEAT_GPIO = 5

# ADC1015 関連定数
I2C_BUSNUM = 1
ADS1015_I2C_BASE_ADDRESS = 0x48
SENSORS = 4
PGA_GAIN = 2
SAMPLING_RATE = 3300

# # データ送信関連定数
# MINIMUM_UPLOAD_QUEUE_LENGTH = 5
# UPLOAD_URL = "https://[データ受信サーバーのホスト名]/whupdate.cgi"
# BASICAUTH_ID = "[基本認証のID]"
# BASICAUTH_PASS = "[基本認証のパスワード]"
# COMPRESSION_LEVEL = 9
